### PR TITLE
 MS_MOVE content under /run, need to differentiate directories from files 

### PR DESCRIPTION
**Pull request by rhatdan**
You can only MS_MOVE a directory to a directory, and a file to a file.
Currently we are only creating directories, so when a user tries to
mount a socket into a container it fails.

docker run -v /run/docker.sock:/run/docker.sock initcontainer
Fails

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@rhvgoyal PTAL
@mrunalp PTAL

**Comment by rhatdan** [comment]
https://github.com/nightvisi0n PTAL

**Comment by rhatdan** [comment]
Fixes https://github.com/projectatomic/oci-systemd-hook/issues/72

**Comment by rhvgoyal** [comment]
Looked at the code and it looks ok. You did a good bug fix in makepath() recursion path. I have not tested it. I am relying on your testing.

LGTM

**Pull request merged**
