### PR TITLE
Fix /var/log/journal for runc containers

### PR DESCRIPTION
**Pull request by giuseppe**

### CODE REVIEW

**Comment by giuseppe** [comment]
@pschiffe, this is to fix the issue you reported, but you will need to specify something like this:

        "env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "TERM=xterm",
            "container=docker",
            "container_uuid=c58cd6f7-6c8a-489a-af19-419597d22fbe"
        ],


in the `config.json`.  At least, until atomic install will facilitate this task and automatically generates an UUID.
My idea is to have something just like: "container_uuid=$UUID"

@rhatdan what do you think of this?

**Comment by rhatdan** [comment]
When you do this does journalctl -M $container_uuid 
Work?

**Comment by rhatdan** [comment]
@mrunalp PTAL

**Comment by giuseppe** [comment]
@rhatdan `journalctl -M $container_uuid` does not work even though the log is correctly written to `/var/log/journal/$CONTAINER_UUID`.  I assumed it requires `oci-register-machine` support for that, but I have not looked into it yet.  Does it work without `oci-register-machine` knowing of these runc containers?

**Comment by mrunalp** [comment]
The first two commits look fine but not convinced that we require container_uuid env variable. The runc id could be set to whatever systemd expects.

**Comment by giuseppe** [comment]
manage the mapping between the name and the uuid could be done by atomic, and use the uuid when "talking" to runc, but it didn't seem as a very generic solution to me (this can be helpful also for not system containers managed by atomic).
The disadvantages I see with using the uuid are that `runc list` won't be as clear is it is now, and commands like `exec` or `kill` will also require to use the uuid.  With this patch managing the uuid part is left to oci-systemd-hook and we can still use a mnemonic name to refer to the container.

**Comment by giuseppe** [comment]
in addition, since the `$container_uuid` is a supported way systemd to assign the systemd machine-id in a container (already used by nspawn).  This patch just adds the support for it and doesn't replace the existing mechanism of using an uuid as the container id.

**Comment by rhatdan** [comment]
@giuseppe lets break the request into separate pull requests, we can merge the first 2 and continue discussions on the third.

**Comment by giuseppe** [comment]
I've moved the third patch here:

https://github.com/projectatomic/oci-systemd-hook/pull/36

**Pull request merged**
