### PR TITLE
Make sure oci-systemd-hook remounts with the correct mount options

### PR DESCRIPTION
**Pull request by rhatdan**
When you run a systemd based container inside of a user namespace,
the mount options have to match exactly those of the existing mount.
So if you remount the mount point, with differenet options, you will
get permission denied.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM, thanks for running this down.

**Comment by rhvgoyal** [comment]
I see another remount call to remount cgroup. What about that.

        if (mount(cgroup_path, cgroup_path, "bind", MS_REMOUNT|MS_BIND|MS_RDONLY, "") == -1) {
                pr_perror("Failed to remount %s readonly", cgroup_path);
                return -1;
        }

**Comment by rhvgoyal** [comment]
May be create a helper function just for remount and use that both in bind_mount() and for cgroup mount.

**Comment by rhatdan** [comment]
@rhvgoyal Added remount_readonly function.

**Comment by rhvgoyal** [comment]
I tested it and it works for me and fixes the remount issues with user namespaces.

LGTM

**Pull request merged**
